name: mindeye
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - aom=3.12.1
  - arrow-cpp=21.0.0
  - async-timeout=5.0.1
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - blas=2.138
  - blas-devel=3.9.0
  - bottleneck=1.4.2
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cuda-cccl_linux-64=12.8.90
  - cuda-crt-dev_linux-64=12.8.93
  - cuda-crt-tools=12.8.93
  - cuda-cudart=12.8.90
  - cuda-cudart-dev=12.8.90
  - cuda-cudart-dev_linux-64=12.8.90
  - cuda-cudart-static=12.8.90
  - cuda-cudart-static_linux-64=12.8.90
  - cuda-cudart_linux-64=12.8.90
  - cuda-cuobjdump=12.8.90
  - cuda-cupti=12.8.90
  - cuda-driver-dev_linux-64=12.8.90
  - cuda-nvcc=12.8.93
  - cuda-nvcc-dev_linux-64=12.8.93
  - cuda-nvcc-impl=12.8.93
  - cuda-nvcc-tools=12.8.93
  - cuda-nvcc_linux-64=12.8.93
  - cuda-nvdisasm=12.8.90
  - cuda-nvrtc=12.8.93
  - cuda-nvtx=12.8.90
  - cuda-nvvm-dev_linux-64=12.8.93
  - cuda-nvvm-impl=12.8.93
  - cuda-nvvm-tools=12.8.93
  - cuda-version=12.8
  - cudnn=9.10.2.21
  - dav1d=1.2.1
  - diffusers-base=0.35.2
  - diffusers-torch=0.35.2
  - expat=2.7.1
  - filelock=3.20.0
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.8.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - h5py=3.15.1
  - harfbuzz=10.2.0
  - hdf5=1.14.6
  - huggingface_accelerate=1.4.0
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - jpeg=9f
  - kernel-headers_linux-64=4.18.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250127.0
  - libaec=1.1.4
  - libavif=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcublas=12.8.4.1
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcufft=11.3.3.83
  - libcurand=10.3.9.90
  - libcurl=8.16.0
  - libcusolver=11.7.3.90
  - libcusparse=12.5.8.93
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm19=19.1.7
  - libmlir19=19.1.7
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libnvjitlink=12.8.93
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsanitizer=14.3.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lit=20.1.8
  - lz4-c=1.9.4
  - magma=2.9.0
  - mkl=2025.0.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.0
  - nccl=2.21.5.1
  - ncurses=6.5
  - networkx=3.4.2
  - nomkl=3.0
  - numexpr=2.14.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.30
  - openssl=3.5.4
  - opentelemetry-api=1.37.0
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=12.0.0
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycares=4.10.0
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytz=2025.2
  - re2=2024.07.02
  - readline=8.3
  - requests=2.32.5
  - s2n=1.5.14
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.5.1
  - snappy=1.2.1
  - sqlite=3.50.2
  - sympy=1.14.0
  - sysroot_linux-64=2.28
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - uvloop=0.22.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - babel==2.17.0
      - beartype==0.22.5
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - braceexpand==0.1.7
      - click==8.3.1
      - clip==1.0
      - clip-anytorch==2.6.0
      - coca-pytorch==0.1.0
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - dalle2-pytorch==1.15.6
      - datasets==4.3.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - deepspeed==0.18.2
      - defusedxml==0.7.1
      - diffusers==0.29.2
      - dill==0.4.0
      - distro==1.9.0
      - einops==0.8.1
      - einx==0.3.0
      - ema-pytorch==0.7.7
      - embedding-reader==1.8.1
      - evaluate==0.4.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - faiss-cpu==1.12.0
      - fastjsonschema==2.21.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozendict==2.4.6
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jiter==0.11.1
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-nvdashboard==0.13.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - kornia==0.7.1
      - lark==1.3.1
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - msgpack==1.1.2
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.13.0
      - nltk==3.8.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open-clip-torch==3.2.0
      - openai==2.7.1
      - opencv-python==4.12.0.88
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - peft==0.17.1
      - pexpect==4.9.0
      - pip==25.3
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - pynvml==12.0.0
      - pyparsing==3.2.5
      - python-json-logger==4.0.0
      - pytorch-lightning==2.0.1
      - pytorch-warmup==0.2.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - resize-right==0.0.2
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rotary-embedding-torch==0.8.9
      - rouge-score==0.1.2
      - rpds-py==0.28.0
      - safetensors==0.7.0
      - scikit-image==0.22.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - send2trash==1.8.3
      - sentence-transformers==2.5.1
      - sentencepiece==0.2.1
      - sentry-sdk==2.43.0
      - sgm==0.1.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.21
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - tomli==2.3.0
      - torch==2.1.0
      - torch-fidelity==0.3.0
      - torchaudio==2.1.0
      - torchmetrics==1.3.0.post0
      - torchvision==0.16.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - transformers==4.41.2
      - triton==2.1.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - umap==0.1.1
      - uri-template==1.3.0
      - vector-quantize-pytorch==1.24.2
      - wandb==0.22.3
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webdataset==0.2.73
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - x-clip==0.14.4
      - xformers==0.0.22.post7
      - xxhash==3.6.0
      - zipp==3.23.0
# prefix removed for portability
